#开发环境
spring:
  profiles:
    active: dev
#生产环境
#@spring.profiles.active=pro
# 设置暴露所有端点
#management.endpoints.web.exposure.include=*
#是否启用安全
#management.security.enabled=false

#启用单独的url来做监控访问入口
#management.context-path=/actuator




